version: "3.8"

services:
  i7100-print-prototype:
    container_name: i7100-print-prototype
    image: i7100-print-prototype:local
    restart: unless-stopped
    ports:
      - "5100:5100"
    environment:
      HOST: 0.0.0.0
      PORT: 5100
      CORS_ORIGIN: "*"
      PRIMARY_PRINTER_IP: 10.145.162.22
      FALLBACK_PRINTER_IP: 10.145.162.32
      PRINTER_PORT: 9100
